/*codigo para o display*/
/* PINO 1 - TERRA
PINO 2 - ALIMENTACAO 5V
PINO 3 - VEE AJUSTA O CONTRASTE DO LCD 
PINO 4 - ESCOLHE ENTRE MODO 
PINO 5 - 0 PARA OPERACAO DE ESCRITA 1 PARA OPERACAO DE LEITURA
PINO 6 - ENABLE 

void init_P2()
{
    
}
